"""adding completed boolean column

Revision ID: 4836171946f7
Revises: a46e968a30d6
Create Date: 2020-04-04 14:24:49.899380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4836171946f7'
down_revision = 'a46e968a30d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean()))
    op.execute('UPDATE todos SET completed = False WHERE completed is NULL;')
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
